version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fastapi_crud
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
